Enable --host and --port as CLI params for custom host and port. READ…
marmelab/json-graphql-server pull request #157
Opened 2023-06-06 22:25 UTC by minupalaniappan

…ME instructions were originally not working

Originally, I was not able to run the JSON GraphQL server at port 5000 with `-p 5000`. 

On this branch, you can now run the the command `./bin/json-graphql-server db.js -p 5000` or  `./bin/json-graphql-server db.js --port 5000`

2023-06-07 12:55 UTC, slax57 requested changes
Thanks for your PR.
However I don't understand the change, which seems to do the opposite of what you describe.
Currently, according to my tests, the script works fine both with `--port 5000` and `-p 5000`.

Now it might be argued that the issue is rather with the `host` parameter, which should be `-h` rather than `--h`, to be consistent with the other parameter and with the docs.

This is what I suggested in this review.

2023-06-07 12:55 UTC, slax57 commented on bin/json-graphql-server.js
> +    if ((arg === '--p' || arg === '--port') && process.argv.length > index + 1) {
```suggestion
    if ((arg === '-p' || arg === '--port') && process.argv.length > index + 1) {
```

2023-06-07 12:55 UTC, slax57 commented on bin/json-graphql-server.js
> +    if ((arg === '--h' || arg === '--host') && process.argv.length > index + 1) {
```suggestion
    if ((arg === '-h' || arg === '--host') && process.argv.length > index + 1) {
```

2023-06-07 17:42 UTC, minupalaniappan commented
Whoops, apologies for the bug in the `--` for `p` and `h`. Your suggestions look fantastic, and I've updated the PR per your comment. Thank you 🤌🏽

2023-06-08 07:44 UTC, slax57 approved these changes
Thanks

2023-06-08 07:44 UTC, merged