Modernize
marmelab/json-graphql-server pull request #178
Opened 2024-07-31 12:49 UTC by djhi

## Description

Modernize the library:

- [x] Convert to TS
- [x] Use Biome for formatting and linting
- [x] Use vitest instead of jest as we already use vite

2025-02-13 10:36 UTC, slax57 requested changes

2025-02-13 10:36 UTC, slax57 commented on Makefile
> +	@yarn run format
why not also add a `lint` target?

2025-02-13 10:36 UTC, slax57 commented on package.json
> +        "lint": "biome lint --apply src",
warning when running this target:

```
⚠ The argument --apply is deprecated, it will be removed in the next major release. Use --write instead.
```

2025-02-13 10:36 UTC, slax57 commented on package.json
> +        "server": "node ./bin/json-graphql-server.js example/data.js",
This script doesn't work.

```
Error: Cannot find module '/home/slax57/workspaces/json-graphql-server/bin/json-graphql-server.js'
```

And `data.js` was renamed to `data.cjs`

2025-02-13 10:36 UTC, slax57 commented on package.json
> +        "format": "biome format --write src",
Running the `format` target changes 3 files. We should commit them.

2025-02-13 10:36 UTC, slax57 commented on src/introspection/getFieldsFromEntities.spec.ts
When opening any test file in my IDE, I see errors like this

```
Cannot find name 'test'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.ts(2582)
```

Although I ran `make install` first and also tried restarting the TS server.

2025-02-14 08:36 UTC, djhi commented on README.md
> +import { jsonGraphqlExpress } from 'json-graphql-server/node';
It is, yes

2025-02-14 14:18 UTC, slax57 reviewed
otherwise everything lgtm

2025-02-14 14:18 UTC, slax57 commented on example/data.mjs
do we need to have both a cjs and an mjs version? :thinking:

2025-02-21 07:55 UTC, slax57 approved these changes

2025-02-21 07:56 UTC, merged